### ISSUE TITLE
eslint version detection issue

### ISSUE THREAD

**Issue by sagiegurari** [bithound/feedback#93]
check https://www.bithound.io/github/sagiegurari/angular-web-notification/blob/2752e8639c579ec3323aa19b15ea199e331c718a/angular-web-notification.js
it says (with a spelling mistake in the unknown by the way):
ESLINT OUTDATEDESLint config version is unkown older than 1.0.0, defaulting to JSHint

but actually my eslintrc is working just fine with latest eslint.
you can view it at:
https://github.com/sagiegurari/angular-web-notification/blob/master/.eslintrc

**Comment by yyx990803** [comment]
Bithound is trying to sniff a ^1.0.0 eslint dependency in `package.json`. Imo this is not a reliable heuristics because people might be linting using the globally-installed CLI, or via a build-plugin.

**Comment by gtanner** [comment]
I agree it isn't a reliable heuristic.

I am currently adding support to sniff out the version of eslint via the gulp and grunt plugins.

Problem is eslint crashes if the schema of the `.eslintrc` file is invalid.  I had to draw the line in the sand somewhere for support, and v1 seemed to be the best place.

Since the `.eslintrc` isn't versioned the only trigger we have to identify if we can run it would be the version of eslint installed via `package.json`.

Moving forward we will attempt to massage and transform the `.eslintrc` based on schema changes and warn on that.

**Comment by sagiegurari** [comment]
i'm not sure why not try to run eslint and if it breaks, run jshint instead?
by the way, v1 eslint from what i remember in the docs and from running it myself with older rules, will not break and will simply print warnings on outdated rules and what replaces them.
so... i'm not sure why not just run eslint instead of trying to find out if you can or can't run it by checking other stuff (which is probably not really possible)

**Comment by sagiegurari** [comment]
All my projects dropped in score in about 8-9 points because of this. That's nice.
Any chance there is a fix coming?

**Comment by gtanner** [comment]
Working on it right now, I am just extending some of our smoke tests to handle some more cases in regards to eslint config detection.  I was going to work on this yesterday but opted to work on https://github.com/bithound/feedback/issues/95 first.

Sorry for the wait.

**Comment by dansilivestru** [comment]
To add to @gtanner with regards to your previous question. You are correct that, on the surface, this does sound like a very proper approach. The issues is always on the periphery though ;) What I mean by that is the following; we have tens of thousands of projects analyzed on bitHound and some of the configurations we've come across cause ESLint to crash in rather catastrophic ways. As a result a more defensive implementation approach was needed.

We'll update this issue as soon we release our fix.

Again thank you for your patience.

**Comment by sagiegurari** [comment]
you sure it crashed? from my experience and eslint docs, from v1 they no longer crash on missing rules.
http://eslint.org/blog/2015/07/eslint-1.0.0-released/#missing-rules-handled-safely

**Comment by dansilivestru** [comment]
Ah, I see. My apologies, I see where I didn't explain myself properly. You are correct that latest ESLint will no longer crash if it comes across missing rules. The issue I was referring to is that in some cases ESLint does crash when trying to parse some old versions/formats of .eslintrc files. We have discovered this in quite a few projects.

**Comment by sagiegurari** [comment]
ok, didn't know that.
but you could use that, meaning if eslint crashes than fallback to jshint. no?

**Comment by jeffcharles** [comment]
My project (at https://www.bithound.io/github/jeffcharles/number-switcher-3000/master) has a dependency on version ^1.3.0 of eslint in my package.json but I'm still seeing an eslint outdated message and the fallback behaviour to jshint.

**Comment by CSilivestru** [comment]
Hi @jeffcharles,

Sorry for the inconvenience -- this was resolved a couple days ago but wouldn't have showed up on your repo until analysis of a new commit. You're all set now and outdated error is gone :-).

**Comment by denis-sokolov** [comment]
@CSilivestru, I still see that with eslint `^1.4.0`.

**Comment by CSilivestru** [comment]
Hi @denis-sokolov,

Sorry for the delay in my response. Our approach to eslint support was a little cautious where we would support new versions as they were released. We've improved this process and you should be much better supported going forward.

**Comment by denis-sokolov** [comment]
Delay? It was only 3 days! Thanks for the reply!
It still shows outdated, but I assume the change needs a few hours/days to propagate.

**Comment by CSilivestru** [comment]
Well I try my best :-).

Would you be willing to share your repo? You can send it to me personally at chris@bithound.io, if you prefer.

I just want to make absolutely sure it's all working for you.

**Comment by denis-sokolov** [comment]
[denis-sokolov/remove-github-forks](https://github.com/denis-sokolov/remove-github-forks), for example.

**Comment by CSilivestru** [comment]
Hi @denis-sokolov,

Your repo is all up to date and looks to be using the correct version of eslint now.
Thanks.

**Comment by sagiegurari** [comment]
It is not solved.
See https://www.bithound.io/github/sagiegurari/multiple-redis/blob/9400e37cb4a8df89bef589179a6b9e9424847176/lib/multiple-redis.js

in package json I have: "grunt-eslint": "latest"
